# Generated by Django 5.2.9 on 2026-02-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='special_instractions',
            new_name='special_instructions',
        ),
    ]
